---
- hosts: localhost
  connection: local
  tasks:
    - name: Gather information about running instances
      ec2_instance_info:
        region: us-east-1
      register: ec2_info

    - name: displaying output of running instances
      debug: 
        msg: "{{ item.instance_id }}"
      with_items: "{{ ec2_info.instances }}"

    - name: terminate
      ec2:
        instance_ids: "{{item.instance_id}}"
        region: us-east-1
        state: absent
        wait: yes
      with_items: "{{ec2_info.instances}}"  

